import MainHeader from "@/components/header/MainHeader";
import "./globals.css";

export const metadata = {
  title: "Imsys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
