import MainHeader from "@/components/header/MainHeader";
import "./globals.css";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Imsys",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
